spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 根据实际情况修改
    gateway:
      discovery:
        locator:
          enabled: true # 开启服务发现自动路由
      routes:
        - id: server-core
          uri: lb://server-core
          predicates:
            - Path=/server-core/**
        - id: proxy-server-starter
          uri: lb://proxy-server-starter
          predicates:
            - Path=/proxy-server/**

server:
  port: 8080

