quarkus:
  application:
    name: qcare-proxy-server
    version: 1.0-SNAPSHOT

  http:
    port: 8080
    host: 0.0.0.0
    cors:
      ~: true
      origins: "*"
      methods: "GET,PUT,POST,DELETE,OPTIONS"
      headers: "X-Requested-With,Content-Type,Accept,Origin,Authorization"

  log:
    level: INFO
    console:
      enable: true
      format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
    category:
      "xyz.firestige.qcare": DEBUG

  websockets:
    # WebSocket配置
    max-frame-size: 65536

  package:
    type: jar

